const ADD_CHARACTER = "ADD_CHARACTER";
const REMOVE_CHARACTER = "DELETE_CHARACTER";
const FILTER = "FILTER"
const ORDER = "ORDER"

export {
    ADD_CHARACTER,
    REMOVE_CHARACTER,
    FILTER,
    ORDER
}