const ADD_CHARACTER = "ADD_CHARACTER";
const REMOVE_CHARACTER = "DELETE_CHARACTER";
const FILTER = "FILTER";
const ORDER = "ORDER";
const GET_FAVORITES = "GET_FAVORITES";

export {
    ADD_CHARACTER,
    REMOVE_CHARACTER,
    FILTER,
    ORDER,
    GET_FAVORITES
}